### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by dzheltkov** [seraya-meduzen/vtm#1]
1) В таблицы нужно добавить времена для реализаций на Фортране.
2) Лучше модифицировать код так, чтобы использовать меньше временной памяти.
3) Для LAPACK тоже нужны таблицы с временами работы для различных порядков.

**Comment by seraya-meduzen** [comment]
все таблицы загружены.
Второй пункт не понял, у меня там просто дополнительные переменные, самых выделений памяти у меня 4 только.

**Comment by dzheltkov** [comment]
std::vector аллоциирует память, поэтому использование временных векторо - это именно аллокация памяти.
То есть можно использовать временные, только их количество можно и нужно сделать меньше.
Но в целом всё хорошо.
